controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

documentation:
    path: /documentation/{file}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        permanent: true
        path: /docs/site/{file}
    requirements:
        file: .*